version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # proxy:
  #   image: caddy:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
  #     - ./data/static:/website/static
  #     - ./data/media:/website/media

  website:
    build: website
    restart: unless-stopped
    volumes:
      - ./data/static:/app/static
      - ./data/media:/app/media
    environment:
      DJANGO_KEY: ${DJANGO_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8000"

