version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


  website:
    build: website
    restart: unless-stopped
    volumes:
      - ./data/media:/website/media
    environment:
      DJANGO_KEY: ${DJANGO_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "6212:8000"
