# Generated by Django 4.2.2 on 2023-06-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="thumb",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
